# Generated by Django 5.2.1 on 2025-05-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
