# Generated by Django 5.2.1 on 2025-05-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_product', '0002_remove_product_slug_delete_productattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='slug',
        ),
    ]
