# Generated by Django 5.2.1 on 2025-05-15 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('weight_limit', models.CharField(blank=True, max_length=100, verbose_name='Лимит веса')),
            ],
            options={
                'verbose_name': 'Весовая категория',
                'verbose_name_plural': 'Весовые категории',
            },
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя Фамилия')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='Прозвище')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fighters/', verbose_name='Изображение')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('country_flag', models.ImageField(blank=True, null=True, upload_to='flags/', verbose_name='Флаг страны')),
                ('is_champion', models.BooleanField(default=False, verbose_name='Чемпион')),
                ('ranking', models.PositiveIntegerField(verbose_name='Ранг')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('height', models.CharField(blank=True, max_length=20, verbose_name='Рост')),
                ('weight', models.CharField(blank=True, max_length=20, verbose_name='Вес')),
                ('reach', models.CharField(blank=True, max_length=20, verbose_name='Размах рук')),
                ('record', models.CharField(blank=True, max_length=50, verbose_name='Рекорд')),
                ('strikes_landed_per_min', models.FloatField(blank=True, null=True, verbose_name='Ударов в минуту')),
                ('strike_accuracy', models.FloatField(blank=True, null=True, verbose_name='Точность ударов')),
                ('takedown_avg', models.FloatField(blank=True, null=True, verbose_name='Среднее количество тейкдаунов')),
                ('takedown_accuracy', models.FloatField(blank=True, null=True, verbose_name='Точность тейкдаунов')),
                ('weight_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighters', to='statistics_fighters.weightcategory', verbose_name='Весовая категория')),
            ],
            options={
                'verbose_name': 'Боец',
                'verbose_name_plural': 'Бойцы',
                'ordering': ['weight_category', 'ranking'],
            },
        ),
    ]
